timezone = "Asia/Tokyo"
start = "22:00"
duration = "1:00"
hashtag = "#SSダンス部"

[days.wednesday]

[languages.en]
name = "SS!Dance Club"

[[join]]
name = "sui（すい）"
id = "usr_f875f33b-6365-41c5-8a55-925e9086e275"
