timezone = "Asia/Tokyo"
start = "21:00"
duration = "2:00"
hashtag = "SSダンス部"
weeks = [1]

[days.wednesday]

[languages.en]
name = "SS!Dance Club"

[[join]]
name = "きたむぅ"
id = "usr_179de95b-409b-4ef6-a934-fadbce3da228"
