name = "VR Dancing NA"
timezone = "CST6CDT"
start = "19:00"
duration = "2:00"
discord = "vrdancing"
twitter = "VRD_Official"
hashtag = "vrdancing"
web = "https://vrdancing.club/"
group = "VRD.9523"

[days.wednesday]
name = "VR Dancing NA Open Session"

[days.saturday]
