name = "VR Dancing AP Open Session"
timezone = "Australia/Sydney"
start = "20:00"
duration = "2:00"
discord = "vrdancing"
twitter = "VRD_Official"
hashtag = "vrdancing"
web = "https://vrdancing.club/"
group = "VRD.9523"

[days.thursday]
