timezone = "Asia/Tokyo"
start = "21:00"
duration = "1:00"
platforms = ["pc", "quest"]
discord = "JVa9VrhQ6U"
hashtag = "VRCフィットボクシング集会"
twitter = "fi_sound"

[[join]]
name = "fiisound（ふぃー）"
id = "usr_397af2fb-2bb9-4f12-837c-4bfcec27e561"

[days.sunday]
