timezone = "Asia/Tokyo"
start = "22:00"
duration = "1:00"
group = "VRCQD.3846"
discord = "AURhgnRT"
weeks = [1, 3, 5]
hashtag = "VRC弓道部"

[[join]]
id = "usr_8a4016f7-7487-4cc5-ae7c-5ea3c3485e58"
name = "ぷちりゅう"

[days.wednesday]
