timezone = "Asia/Tokyo"
start = "22:00"
duration = "1:00"
group = "VRP.4653"
discord = "NCq7kvtCMJ"
hashtag = "はれクラス"

[[join]]
name = "Hare0829"
id = "usr_db682464-a4c5-47bf-8300-9b9dd1bf451f"

[days.wednesday]
