timezone = "Asia/Tokyo"
start = "22:00"
duration = "0:45"
group = "VRP.4653"
discord = "NCq7kvtCMJ"
hashtag = "まおりんクラス"

[[join]]
name = "柘榴石まおりん"
id = "usr_1f1032f1-83c9-4fea-bf47-02c683f38e43"

[days.monday]
start = "22:00"

[days.thursday]
start = "21:00"

[days.saturday]
start = "8:30"
duration = "1:00"
