timezone = "Asia/Tokyo"
start = "20:30"
duration = "1:00"
group = "VRP.4653"
discord = "NCq7kvtCMJ"
hashtag = "たみクラス"
canceled = [
    "2023-07-3",
    "2023-07-10",
    "2023-07-17",
    "2023-07-24",
    "2023-07-31",
]

[[join]]
name = "たみ（People）"
id = "usr_f78df0e3-821c-467c-934d-ae6bcd91eebd"

[days.monday]
