timezone = "Asia/Tokyo"
start = "22:00"
duration = "1:00"
group = "VRP.4653"
discord = "NCq7kvtCMJ"
hashtag = "#のりおクラス"

[[join]]
name = "のりお709"
id = "usr_dbdcba38-c0a5-4f42-9513-f45aef07f368"

[days.wednesday]
