timezone = "Asia/Tokyo"
start = "19:30"
duration = "0:45"
group = "KUREUN.7765"
platforms = ["pc", "quest"]
twitter = "@kureun_official"
hashtag = "#くれ運"

[[join]]
name = "くれこ（kureko）"
id = "usr_35e7ce3e-78f9-4fc7-ad48-8933ce4a206c"
