timezone = "Asia/Tokyo"
start = "21:30"
duration = "1:00"
hashtag = "ゆるふわパラパラ部"
twitter = "yuru_para"
group = "PARA.6038"
platforms = ["pc", "quest"]

canceled = [
  "2023-05-17"
]

[[join]]
name = "Izumi_Mizuha"
id = "usr_f48cd0d4-dad6-4cc9-a650-ff077ac103fa"

[days.wednesday]

