timezone = "Asia/Tokyo"
start = "20:45"
duration = "0:30"
hashtag = "夏季巡回VRChatラジオ体操"
twitter = "January183"
start_date = "2023-08-01"
end_date = "2023-08-31"
confirmed = [
    "2023-08-01",
    "2023-08-02",
    "2023-08-03",
    "2023-08-04",
    "2023-08-06",
    "2023-08-07",
]
canceled = [
    "2023-08-05",
]

[[join]]
name = "Kote_Janxrf"
id = "usr_b3c46baa-4bd8-4dbf-ba2c-7e2efdadef20"
